### ISSUE TITLE
Cannot browserify fontkit

### ISSUE THREAD

**Issue by bernharduw** [devongovett/fontkit#1]
I tried to install the fontkit branch of pdfkit, but I am getting errors from a browserify (on Mac OS X Yosemite). I cannot find a reference to a module called `ws` in the code, so I really have no idea what the problem is.

I even tried to use older browserify versions in case this is a bug of browserify, but with no success. Maybe you have an idea?

````bash
$ browserify test.js
Cannot find module 'ws' from '/Users/xy/Documents/repos/test-fontkit/node_modules/fontkit/node_modules/brotli'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:50:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:119:43)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:128:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:43)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:66:22
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:108:15)

$ npm ls
/Users/xy/Documents/repos/test-fontkit
└─┬ fontkit@1.0.2
  ├── brotli@1.0.0
  ├── lodash@2.4.1
  ├── pako@0.2.5
  ├─┬ restructure@0.1.11
  │ └── iconv-lite@0.4.6
  └─┬ typedarray-to-buffer@3.0.1
    └── is-typedarray@0.0.0

$ cat test.js 
var fontkit = require('fontkit');

$ browserify -v
8.1.3

````

**Comment by devongovett** [comment]
First off, thanks for trying the fontkit branch. Looks like the issue is with [brotli.js](https://github.com/devongovett/brotli.js). I haven't tried with browserify yet, but my guess is that it's an issue with the Emscripten compile where it thinks it's inside Node, but it's really in browserify. I'll look into it.

**Comment by bernharduw** [comment]
Thanks! In the meantime I manually commented out the WOFF2 support and this works.

Nevertheless I seem to have some font issues with the fontkit version. I will send you the generated pdfs via PM if that's ok!

**Comment by devongovett** [comment]
Go for it: devongovett@gmail.com.
