### ISSUE TITLE
Fonts without name ID 6 (Postscript name) don’t work

### ISSUE THREAD

**Issue by khaledhosny** [devongovett/fontkit#111]
Using the file [Mada-Regular.zip](https://github.com/devongovett/fontkit/files/1066592/Mada-Regular.zip) gives this backtrace:
```
TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at WOFF2Font.get (/home/khaled/fk/node_modules/fontkit/index.js:13904:18)
    at /home/khaled/fk/fontkit-render:35:28
    at Array.map (native)
    at render (/home/khaled/fk/fontkit-render:30:27)
    at Object.<anonymous> (/home/khaled/fk/fontkit-render:73:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

Which seems because fontkit is trying to read the PostScript name unconditionally while the font does not have it (the font was created by `pyftsubset` with default options).

**Comment by Pomax** [comment]
Interesting. I remember [running into an issue of ids 1-6](https://stackoverflow.com/questions/21801855/what-are-the-windows-requirements-for-an-opentype-font-to-be-installable) where it turned out that without 3 and 6, fonts can't be installed on Windows. While fontkit should probably not break on a missing id:6, it would also be worth notifying whomever made that font that id:6 is fairly important and worth adding in with a new version release.

**Comment by khaledhosny** [comment]
See above, the font was subset with `pyftsubset` from FontToo;s with default options. The subsetter is rather tuned by default for web fonts where the name table is redundant, and one can still select which name ids to keep. I don’t think FontKit should crash or even raise an error for such fonts (except may be when the PostScript name is really needed i.e. in call sites that absolutely require it). Both FreeType and HarfBuzz has no problem using this font.

**Comment by Pomax** [comment]
ah, missed that for some reason.
