### ISSUE TITLE
Loading some fonts produces error.

### ISSUE THREAD

**Issue by jsieler** [devongovett/fontkit#22]
Hello!
We have a bunch of font which are producing error. Following:

```
/root/fontserver/node_modules/fontkit/node_modules/brotli/build/decode.js:1
function e(a){throw a;}var j=void 0,m=!0,p=null,s=!1,t,v={};v.readBinary=require("../src/read_memory");v||(v=eval("(function() { try { return Module || {} } catch(e) { return {} } })()"));var aa={},w;for(w in v)v.hasOwnProperty(w)&&(aa[w]=v[w]);var ba="object"===typeof process&&"function"===typeof require,ca="object"===typeof window,da="function"===typeof importScripts,ea=!ca&&!ba&&!da;
              ^

TypeError: Cannot read property '26979' of undefined
    at Object.r.Struct.string.r.Pointer.type (/root/fontserver/node_modules/fontkit/src/tables/name.js:14:40)
    at StringT.decode (/root/fontserver/node_modules/fontkit/node_modules/restructure/src/String.js:30:29)
    at /root/fontserver/node_modules/fontkit/node_modules/restructure/src/Pointer.js:69:30
    at Pointer.decode (/root/fontserver/node_modules/fontkit/node_modules/restructure/src/Pointer.js:79:16)
    at Struct._parseFields (/root/fontserver/node_modules/fontkit/node_modules/restructure/src/Struct.js:53:22)
    at Struct.decode (/root/fontserver/node_modules/fontkit/node_modules/restructure/src/Struct.js:18:12)
    at ArrayT.decode (/root/fontserver/node_modules/fontkit/node_modules/restructure/src/Array.js:49:30)
    at VersionedStruct.Struct._parseFields (/root/fontserver/node_modules/fontkit/node_modules/restructure/src/Struct.js:53:22)
    at VersionedStruct.decode (/root/fontserver/node_modules/fontkit/node_modules/restructure/src/VersionedStruct.js:42:12)
    at TTFFont._decodeTable (/root/fontserver/node_modules/fontkit/src/TTFFont.js:93:32)
```
That happens only while we trying to get font name (full or postscript).

Any fix on that?! Thanks!

**Comment by Pomax** [comment]
Do you have a snippet that shows the code you're using that leads to this error? (e.g. some simplified code that just loads in your font, then tries to do the thing you try to do that leads to this error directly, without anything else that happens around it in your own program(s)?)

**Comment by jsieler** [comment]
Hello! Sorry for not replying that long. Here is the code.

`var fontkit = require('fontkit');
var wrench = require('wrench');
var path = require('path');

install_fonts('/mnt/fonts/B');

function install_fonts(directory) {
  // Recursively read directories contents
  var fileslist = wrench.readdirSyncRecursive(directory);

  for(var i in fileslist) {
    var file = directory + '/' + fileslist[i];
    var ext = getExtension(file);

    if(ext == '.ttf' || ext == '.otf') {
      fontkit.open(file, function(err, font) {
        if(!err && font) {
          console.log(font.postscriptName);
        }
      });
    }
  }
}

function getExtension(filename) {
  return path.extname(filename).toLowerCase();
}
`

**Comment by devongovett** [comment]
Can you tell what font is causing the issue? Looks like possibly a bad `name` table.
