### ISSUE TITLE
Can't layout in TravelingTypewriter.otf font

### ISSUE THREAD

**Issue by defue** [devongovett/fontkit#27]
Here is the code:
```
var fontkit = require('fontkit');
var font = fontkit.openSync('TravelingTypewriter.otf');
var run = font.layout('hello world!');
```

Here is the output:
```
/home/user/node_modules/fontkit/node_modules/brotli/build/decode.js:1
orts, require, module, __filename, __dirname) { function e(a){throw a;}var j=v
                                                                    ^
Error: Not a fixed size
    at Object.exports.resolveLength (/home/user/node_modules/fontkit/node_modules/restructure/src/utils.js:19:13)
    at ArrayT.decode (/home/user/node_modules/fontkit/node_modules/restructure/src/Array.js:22:24)
    at VersionedStruct.Struct._parseFields (/home/user/node_modules/fontkit/node_modules/restructure/src/Struct.js:53:22)
    at VersionedStruct.decode (/home/user/node_modules/fontkit/node_modules/restructure/src/VersionedStruct.js:42:12)
    at /home/user/node_modules/fontkit/node_modules/restructure/src/Pointer.js:69:30
    at CFFPointer.Pointer.decode (/home/user/node_modules/fontkit/node_modules/restructure/src/Pointer.js:79:16)
    at CFFPointer.decode (/home/user/node_modules/fontkit/src/cff/CFFPointer.js:30:42)
    at decodeOperands (/home/user/node_modules/fontkit/src/cff/CFFDict.js:36:21)
    at CFFDict.decode (/home/user/node_modules/fontkit/src/cff/CFFDict.js:96:27)
    at CFFIndex.decode (/home/user/node_modules/fontkit/src/cff/CFFIndex.js:42:30)
```

The font is attached. Fontkit version is 1.1.0.

[TravelingTypewriter.otf.zip](https://github.com/devongovett/fontkit/files/142102/TravelingTypewriter.otf.zip)

**Comment by Pomax** [comment]
it you're pasting blocks of code, rather than using single backticks for inline code, you can use three backticks on their own line to start a code block that preserves newlines, and then end the block with another three backticks on their own line.

**Comment by Pomax** [comment]
running locally I get the same result
```
$> node test

node_modules\brotli\build\decode.js:1
(function (exports, require, module, __filename, __dirname) { function e(a){throw a;}var j=void 0,m=!0,p=null,s=!1,t,v={};v.readBinary=require("../src/read_memory");v||(v=eval("(function() { try { return Module || {} } c
atch(e) { return {} } })()"));var aa={},w;for(w in v)v.hasOwnProperty(w)&&(aa[w]=v[w]);var ba="object"===typeof process&&"function"===typeof require,ca="object"===typeof window,da="function"===typeof importScripts,ea=!ca
&&!ba&&!da;
                                                                            ^

Error: Not a fixed size
    at Object.exports.resolveLength (node_modules\restructure\src\utils.js:19:13)
    at ArrayT.decode (node_modules\restructure\src\Array.js:22:24)
    at VersionedStruct.Struct._parseFields (node_modules\restructure\src\Struct.js:53:22)
    at VersionedStruct.decode (node_modules\restructure\src\VersionedStruct.js:42:12)
    at node_modules\restructure\src\Pointer.js:69:30
    at CFFPointer.Pointer.decode (node_modules\restructure\src\Pointer.js:79:16)
    at CFFPointer.decode (node_modules\fontkit\src\cff\CFFPointer.js:30:42)
    at decodeOperands (node_modules\fontkit\src\cff\CFFDict.js:36:21)
    at CFFDict.decode (node_modules\fontkit\src\cff\CFFDict.js:96:27)
    at CFFIndex.decode (node_modules\fontkit\src\cff\CFFIndex.js:42:30)
```

**Comment by defue** [comment]
Any chances it will be fixed?

**Comment by devongovett** [comment]
Sorry, I haven't had time yet. I'll try to look today.

**Comment by devongovett** [comment]
Should be fixed by the above PR. Published to npm as v1.2.1. Sorry for the delay in looking at this!

**Comment by devongovett** [comment]
As for the brotli decoder appearing in the stack trace, that's due to emscripten eating all JS errors. Pretty annoying.

**Comment by defue** [comment]
devongovett, thank you very much for the fix!
