### ISSUE TITLE
Can't require

### ISSUE THREAD

**Issue by josip** [devongovett/fontkit#29]
Just did `npm install fontkit`, and tried to require it in node CLI but got this:

```
> require('fontkit');
TypeError: Cannot call method 'replace' of undefined
    at Object.<anonymous> (/Users/josip/tmp/node_modules/fontkit/node_modules/brotli/build/decode.js:2:462)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/josip/tmp/node_modules/fontkit/node_modules/brotli/decompress.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

I'm using node 0.10.4 on OS X 10.11. I'm guessing I'm using a too old version of node?

**Comment by devongovett** [comment]
It is emscripten being stupid again. It is looking for the program name (normally `process.argv[1]`), but there is none since you just typed `node` without an argument. It works outside the cli. I'm working to move away from emscripten for brotli decoding.

**Comment by Pomax** [comment]
However, that said, yes: 0.10 is too old =) v0.12 is about to fall out of its LTS periodd, so you want to be on v4.x (current long-term-support version is 4.4) or 5.x (current stable being 5.9)

**Comment by devongovett** [comment]
This should be fixed if you re-install. We're using a hand ported pure JS brotli decoder now.
