### ISSUE TITLE
Error: Unknown version 128

### ISSUE THREAD

**Issue by defue** [devongovett/fontkit#30]
Code:
```
var fontkit = require('fontkit');
var font = fontkit.openSync('Verona-Xlight.ttf');
var run = font.layout('hello world!');
```

Output:
```
/home/defue/node_modules/brotli/build/decode.js:1
orts, require, module, __filename, __dirname) { function e(a){throw a;}var j=v
                                                                    ^
Error: Unknown version 128
    at VersionedStruct.decode (/home/defue/node_modules/restructure/src/VersionedStruct.js:37:15)
    at VersionedStruct.Struct._parseFields (/home/defue/node_modules/restructure/src/Struct.js:53:22)
    at VersionedStruct.decode (/home/defue/node_modules/restructure/src/VersionedStruct.js:42:12)
    at ArrayT.decode (/home/defue/node_modules/restructure/src/Array.js:49:30)
    at VersionedStruct.Struct._parseFields (/home/defue/node_modules/restructure/src/Struct.js:53:22)
    at VersionedStruct.decode (/home/defue/node_modules/restructure/src/VersionedStruct.js:42:12)
    at TTFFont._decodeTable (/home/defue/node_modules/fontkit/src/TTFFont.js:93:32)
    at TTFFont.getTable (/home/defue/node_modules/fontkit/src/TTFFont.js:69:40)
    at LayoutEngine.position (/home/defue/node_modules/fontkit/src/layout/LayoutEngine.js:106:72)
    at LayoutEngine.layout (/home/defue/node_modules/fontkit/src/layout/LayoutEngine.js:63:24)
```
The font is attached. 
[Verona-Xlight.ttf.zip](https://github.com/devongovett/fontkit/files/179837/Verona-Xlight.ttf.zip)

Fontkit version 1.2.1

**Comment by devongovett** [comment]
Looks like that font has a bad kern table. I get an error reading it with [fonttools](https://github.com/behdad/fonttools) as well.

**Comment by devongovett** [comment]
Apple's ftxdumperfuser generates this output:

```xml
<KERNTable version="0" subtableCount="1" >
	<kernSubtable format="0" version="0" length="6" coverage="0x8000" kernVertical="yes" kernMinimum="no" kernCrossStream="no" kernOverride="no" >
	</kernSubtable>
</KERNTable>
```

The length of the subtable is too short.

**Comment by defue** [comment]
Can't this error just be ignored? For example this font works perfectly in Ubuntu.

**Comment by devongovett** [comment]
As of the above commit, table decoding errors are caught and optionally logged if `fontkit.logErrors` is true.

This does have the unfortunate side effect that most of the time, you won't even know if a table failed to decode, which could be because of a bug in fontkit or actually because of a bad table. So I was a little hesitant to add this since it will result in less bugs being reported and fixed. I might still turn on logging by default. That would not stop your program from running correctly, but might help with bug reporting. Thoughts?
