### ISSUE TITLE
Error when building fontkit

### ISSUE THREAD

**Issue by defue** [devongovett/fontkit#62]
I've downloaded the master branch and try to build it by issuing the below commands"

```
cd fontkit-master
make
```
Here is the output I get:
```
babel-node src/opentype/shapers/gen-use.js
/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:334
        throw e;
        ^

TypeError: Cannot read property 'merge' of undefined (While processing preset: "/home/defue/Temp/fontkit/node_modules/babel-preset-es2015/lib/index.js")
    at Object.<anonymous> (/home/defue/Temp/fontkit/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:52:32)
    at Module._compile (module.js:410:26)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/defue/Temp/fontkit/node_modules/babel-plugin-transform-es2015-classes/lib/loose.js:21:16)
    at Module._compile (module.js:410:26)
Makefile:9: recipe for target 'src/opentype/shapers/use.trie' failed
make: *** [src/opentype/shapers/use.trie] Error 1
```
babel-node version 6.18.0

**Comment by indolering** [comment]
I'm not getting this ... Make runs raw Unix commands, so you have to have rollup, etc installed globally.

Very old ticket, close?

**Comment by defue** [comment]
Not relevant for me now. Please close.
